# Generated by Django 4.1.7 on 2023-02-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department_id',
            new_name='department',
        ),
    ]
